### Bài 3: Load Balancing với Nginx + Flask
version: "3.8"
services:
    flask1:
        build: ./flask_app
        ports:
            - "5001:5000"
        networks:
            - flask_network
    flask2:
        build: ./flask_app
        ports:
            - "5002:5000"
        networks:
            - flask_network
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - flask1
            - flask2
        networks:
            - flask_network
networks:
    flask_network:
