### Bài 4: Prometheus + Grafana Monitoring
version: "3.8"
services:
    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        ports:
            - "9090:9090"
        networks:
            - monitoring
    grafana:
        image: grafana/grafana
        volumes:
            - grafana_data:/var/lib/grafana
        ports:
            - "3000:3000"
        networks:
            - monitoring
volumes:
    prometheus_data:
    grafana_data:
networks:
    monitoring:
