### Bài 7: Chạy MongoDB và Mongo Express
version: "3.8"
services:
    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
    mongo-express:
        image: mongo-express
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
        ports:
            - "8083:8081"
        depends_on:
            - mongodb
