### Bài 2: Ứng dụng Node.js + MongoDB
version: "3.8"
services:
    mongodb:
        image: mongo:latest
        volumes:
            - mongo_data:/data/db
        networks:
            - app_network
        healthcheck:
            test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
            interval: 10s
            retries: 5
    nodeapp:
        build: .
        depends_on:
            mongodb:
                condition: service_healthy
        ports:
            - "3000:3000"
        networks:
            - app_network
volumes:
    mongo_data:
networks:
    app_network:
